spring:
  application:
    name: creama-backend
    
  datasource:
    url: jdbc:mariadb://localhost:3306/creama_db
    username: root
    password: skymp159
    driver-class-name: org.mariadb.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        
server:
  port: 8081
  
logging:
  level:
    com.creama: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
